#pragma once

// Basic ESP32-S3 configs
#define CONFIG_IDF_TARGET_ESP32S3 1
#define CONFIG_IDF_TARGET "esp32s3"
#define CONFIG_IDF_FIRMWARE_CHIP_ID 0x0009

// Flash configs
#define CONFIG_ESPTOOLPY_FLASHMODE_QIO 1
#define CONFIG_ESPTOOLPY_FLASHMODE "qio"
#define CONFIG_ESPTOOLPY_FLASHFREQ_80M 1
#define CONFIG_ESPTOOLPY_FLASHFREQ "80m"

// CPU configs
#define CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240 1
#define CONFIG_ESP32S3_DEFAULT_CPU_FREQ_MHZ 240

// PSRAM configs
#define CONFIG_SPIRAM 1
#define CONFIG_SPIRAM_MODE_QUAD 1
#define CONFIG_SPIRAM_SPEED_80M 1

// Cache configs
#define CONFIG_ESP32S3_DATA_CACHE_32KB 1
#define CONFIG_ESP32S3_DATA_CACHE_SIZE 0x8000
#define CONFIG_ESP32S3_DATA_CACHE_LINE_32B 1
#define CONFIG_ESP32S3_DATA_CACHE_LINE_SIZE 32

// Arduino specific configs
#define CONFIG_AUTOSTART_ARDUINO 1
#define CONFIG_ARDUINO_RUNNING_CORE 1
#define CONFIG_ARDUINO_LOOP_STACK_SIZE 8192